chinese/urls.py
from django.urls import path, include
from . import views
app_name = 'chinese'
urlpatterns = [
    path("add_food/", views.add_food,name='add_food'),
    path("food_detail/<int:pk>/", views.food_detail,name='food_detail'),
    path("food_delete/<int:pk>/", views.food_delete,name='food_delete'),    
    # path("upload/", views.upload),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'main'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path("food/", include("chinese.urls")),
    path("customer/", include("customer.urls")),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path, include
from . import views
app_name = 'customer'
urlpatterns = [
    path("", views.customer_index,name='index'),
    path("food_detail/<int:pk>/", views.food_detail,name='food_detail'),
    # path("add_cart/",views.add_cart,name='add_cart'), # 장바구니 넣기
    # path("remove_cart/",views.remove_cart,name='remove_cart') # 장바구니 빼기
    path("modify_cart/",views.modify_cart,name='modify_cart') # 장바구니 빼기
    ]

chinese/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)
    
class Food(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    price = models.IntegerField()
    description = models.TextField(max_length=100)
    image_url = models.URLField()

customer/models.py
from django.db import models
from chinese.models import Food
# Create your models here.
# 어떤 음식을 얼마나 카트에 담았나?

# table 생성되는 default이름: customer_cart (프로젝트이름_모델이름)  
class Cart(models.Model):
    food = models.ForeignKey(Food,on_delete=models.DO_NOTHING )
    amount =models.IntegerField(default=0)
    

chinese/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Food
from .models import Category
from django.core.files.storage import FileSystemStorage
# Create your views here.

# def upload(request):
#     fs = FileSystemStorage()
#     uploaded_file = request.FILES['file']
#     name = fs.save(uploaded_file.name, uploaded_file) #파일 저장
#     url = fs.url(name) # 파일 경로를 받아서 DB에 저장
#     return HttpResponse("{}에 저장이 잘 되었습니다.".format(url))
    
    
    
    
def add_food(request):
    if request.method=='GET':
        return render(request=request, template_name='chinese/add_food.html')
    elif request.method =='POST':
        # Category 인스턴스 가져오는 영역
        category = Category.objects.get(name=request.POST['category'])

        # Food 내용을 구성 영역
        food_name = request.POST['lion_name']
        food_price = request.POST['price']
        food_description = request.POST['description']
        
        # 이미지 저장 및 url 설정 내용
        fs=FileSystemStorage()
        uploaded_file = request.FILES['file']
        name = fs.save(uploaded_file.name, uploaded_file)
        url = fs.url(name)

        Food.objects.create(category= category,name=food_name, price =food_price , description=food_description,image_url=url)        
        return redirect('index')  
    
    
def food_delete(request, pk):
    object = Food.objects.get(pk=pk)
    object.delete()
    return redirect('index') 

def food_detail(request, pk):
    object = Food.objects.get(pk=pk)
    context = {
        'object':object
    }
    return render(request, 'chinese/food_detail.html', context)

config/views.py
from django.shortcuts import render
from chinese.models import Category, Food

def index(request):
    category = Category.objects.all()
    food = Food.objects.all()
    context = {
        "category":category,
        'food':food
    }
    return render(request, 'index.html',context)

customer/views.py
from django.shortcuts import render
from chinese.models import Category, Food
from .models import Cart
# Create your views here.
def customer_index(request):
    # category, food 보내줘야 돼 -> category만 가져와도 food 가져와짐(foreignkey)
    category = Category.objects.all()
    context={
        'category' : category
    }
    return render(request,'customer/index.html',context)

def food_detail(request,pk):
    # object 필요함
    food = Food.objects.get(pk=pk)
    context={
        'object': food
    }
    return render(request, 'customer/customer_detail.html',context)

def add_cart(request):
    # Cart food_id에 대응되는 데이터의 수량을 add 하다(하나 올려라)
    food_id = request.GET['food_id']
    food = Food.objects.get(pk=food_id)
    # 이전에 해당 음식에 대한 장바구니 정보가 있으면 get
    # 없으면 새로 생성해서 적용
    try:
        cart = Cart.objects.get(food=food)
    except:
        cart = Cart.objects.create(food=food)
    finally:
        pass
    cart.amount+=1
    cart.save()
    context = {
        'object':food
    }
    return render(request, 'customer/customer_detail.html',context )

def remove_cart(request):
    food_id= request.GET['food_id']
    food = Food.objects.get(pk=food_id)
    cart = Cart.objects.get_or_create(food=food)
    # cart, created = Cart.objects.get_or_create(food=food)    
    cart, _ = Cart.objects.get_or_create(food=food)   
    cart.amount-=1
    cart.save()
    context = {
        'object':food
    }
    return render(request, 'customer/customer_detail.html',context )

from django.http import JsonResponse
def modify_cart(request):
    # 어떤 음식(food_id)에 amount를 amountChange만큼 변경하고 -> 개발하기
    food_id= request.POST['foodId']
    food = Food.objects.get(pk=food_id)
    cart, _ = Cart.objects.get_or_create(food=food)
    cart.amount+=int(request.POST['amountChange'])
    if cart.amount>0:
        cart.save()
    # 변경된 최종 결과를 반환(JSON 형식)
    context={
        'newQuantity': cart.amount,
        'message':'수량이 성공적으로 업데이트 되었습니다.',
        'success':True
    }
    return JsonResponse(context)
    # request.POST : <QueryDict: {'foodId': ['4'], 'amountChange': ['1']}> 기반으로 위 내용 ->

chinese/templates/chinese/add_food.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lion 중화요리</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    .img-preview {
        width: 100%;
        max-width: 200px; /* 이미지 미리보기 크기 설정 */
        height: auto;
        margin-top: 10px;
    }
</style>
</head>
<body>
<div class="container mt-5">
    <h1 class="text-center mb-4">Lion 중화요리에 오신 것을 환영합니다!!</h1>

    <form action="" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="row g-3 mb-3">
            <div class="col-md-4">
                <label for="category" class="form-label">카테고리 선택:</label>
                <select name="category" class="form-select">
                    <option value="면류">면류</option>
                    <option value="식사류">식사류</option>
                    <option value="요리류">요리류</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="name" class="form-label">음식이름:</label>
                <input type="text" name="lion_name" class="form-control" id="name">
            </div>
            <div class="col-md-4">
                <label for="price" class="form-label">가격:</label>
                <input type="text" name="price" class="form-control" id="price">
            </div>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">소개:</label>
            <textarea name="description" rows="4" class="form-control"></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">사진을 올려주세요</label>
            <input type="file" name="file" class="form-control" id="file" onchange="previewFile()">
            <img id="preview" src="" class="img-preview" alt="Image preview">
        </div>
        <div class="text-center">
            <input type="submit" value="제출" class="btn btn-success">
        </div>
    </form>
</div>

<!-- Bootstrap JS with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</script>
</body>
</html>

chinese/templates/chinese/food_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>상세 정보</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    .product-image {
        width: 100%;
        height: 300px;
        object-fit: cover;
    }
</style>
</head>
<body>
<div class="container my-5">
    <h1 class="display-4 mb-3">{{ object.category.name }}</h1>
    <h2 class="mb-2">{{ object.name }}</h2>
    <h3 class="text-muted mb-3">{{ object.price }}원</h3>
    <img src="{{ object.image_url }}" alt="{{ object.name }}" class="product-image mb-3">
    <p>{{ object.description }}</p>

    <form action="{% url 'chinese:food_delete' pk=object.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제하기</button>
    </form>
</div>

<!-- Bootstrap JS with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

customer/templates/customer/customer_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>제품 상세 정보(고객용)</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    .product-image {
        width: 100%; /* 이미지 너비를 컨테이너에 맞춤 */
        height: auto; /* 이미지 높이를 자동으로 설정하여 비율 유지 */
        margin-bottom: 20px;
    }
    .info-section {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 5px;
    }
    .btn-custom {
        background-color: #dc3545;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    .btn-custom:hover {
        background-color: #c82333;
    }
</style>
</head>
<body>
    <div>
        <button type="button" class="btn btn-primary">
            장바구니 <span class="badge bg-secondary"><span id="currentQuantity"></span></span>
          </button>
    </div>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ object.image_url }}" alt="{{ object.name }}" class="product-image">
        </div>
        <div class="col-md-6 info-section">
            <h1>{{ object.category.name }}</h1>
            <h2>{{ object.name }}</h2>
            <h3 class="text-muted">{{ object.price }}원</h3>
            <p>{{ object.description }}</p>
        </div>
    </div>
</div>
<div  class="container">
    <input type="hidden" id="csrfToken" value="{{csrf_token}}">
<button type="button" onclick="modifyCartAmount({{object.id}}, 1)" class="btn btn-danger">담기</button>
<button type="button" onclick="modifyCartAmount({{object.id}}, -1)" class="btn btn-success">빼기</button>
</div>
<!-- Bootstrap JS with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script>
    function getCsrfToken(){
        return document.getElementById('csrfToken').value;
    }
    function modifyCartAmount(food_id, change){
        var xhr = new XMLHttpRequest();
            xhr.open('POST', '{% url "customer:modify_cart" %}', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', getCsrfToken());

            xhr.onload = function() {
                if (this.status === 200) {
                    var response = JSON.parse(this.responseText);
                    document.getElementById('currentQuantity').textContent = response.newQuantity;
                    console.log('Update successful:', response.message);
                } else {
                    console.error('Error updating:', this.statusText);
                }
            };
            xhr.send(`foodId=${food_id}&amountChange=${change}`);
    }
</script>
</body>
</html>

customer/templates/customer/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>중화요리집 고객 페이지에 오신것을 환영합니다!</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    .food-image {
        width: 100%; /* 이미지를 카드의 너비에 맞춤 */
        height: 200px; /* 이미지 높이 고정 */
        object-fit: cover; /* 이미지 비율을 유지하면서 요소에 맞춤 */
    }
</style>
</head>
<body>
<div class="container mt-5">
    <h1 class="mb-3 text-center">Lion 중화요리집(고객페이지)에 오신 것을 환영합니다.</h1>

    <div class="row">
        <div class="col-md-6">
            <h3>카테고리</h3>
            <ul class="list-group">
            {% for cat in category %}
                <li class="list-group-item">{{ cat.name }}</li>
                {% for food in cat.food_set.all %}
                <div class="col-sm-6 col-md-4 mb-4">
                    <div class="card">
                        <a href="{% url 'customer:food_detail' pk=food.id %}">
                            <img src="{{ food.image_url }}" class="card-img-top food-image" alt="{{ food.name }}">
                            <div class="card-body row">
                                <h5 class="card-title">{{food.name }}</h5>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!-- Bootstrap JS with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>중화요리집</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    .food-image {
        width: 100%; /* 이미지를 카드의 너비에 맞춤 */
        height: 200px; /* 이미지 높이 고정 */
        object-fit: cover; /* 이미지 비율을 유지하면서 요소에 맞춤 */
    }
</style>
</head>
<body>
<div class="container mt-5">
    <h1 class="mb-3 text-center">우리 중화요리집에 오신 것을 환영합니다.</h1>

    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'chinese:add_food' %}" class="btn btn-primary">제품 등록</a>
    </div>

    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'customer:index' %}" class="btn btn-primary">고객 페이지로 이동</a>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h3>카테고리</h3>
            <ul class="list-group">
            {% for cat in category %}
                <li class="list-group-item">{{ cat.name }}</li>
            {% endfor %}
            </ul>
        </div>

        <div class="col-md-8">
            <h3>음식</h3>
            <div class="row">
            {% for f in food %}
                <div class="col-sm-6 col-md-4 mb-4">
                    <div class="card">
                        <a href="{%url 'chinese:food_detail' pk=f.id%}">
                            <img src="{{ f.image_url }}" class="card-img-top food-image" alt="{{ f.name }}">
                            <div class="card-body row">
                                <h5 class="card-title">{{ f.name }}</h5>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>